# Site settings
baseurl = "https://st-wong.github.io/"
languageCode = "en-us"
title = "Career timeline of Shin Tatt, Wong"
theme = "spectre-pixel"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-29809648-1"

[params]
  name = "Shin Tatt, Wong"
  altName = "黃晟達"
  description = "Work of Shin Tatt"
  bio = "Full Stack developer."
  enableRSS = true
  
  # Sharing options and author information in posts
  aboutAuthor = "I'm a Devloper."
  
  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [
    "https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css"
  ]
  customJS  = []
  
  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.
  
  # Navigation links
  home = ""
  subscribe = ""
  
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  copyright = ""
  
  # 404 page
  title404 = ""
  subtitle404 = ""

# Add additional social link entries underneath
[social]
  email    = "shintatt.wong@gmail.com"
  facebook = "https://www.facebook.com/shintatt"
  github   = "https://www.github.com/st-wong"
  linkedin = "https://www.linkedin.com/in/ShinTatt"
  twitter  = "https://www.twitter.com/shintatt"

[taxonomies]
  tag = "tags"
